[package]
name = "sfce"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
chumsky = "1.0.0-alpha.7"
clap = { version = "4.5.21", features = ["derive"] }
fumen = "0.1.2"
itertools = "0.13.0"
open = "5.3.1"
rayon = "1.10.0"
strum = { version = "0.26.3", features = ["derive"] }
